controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login

cgu:
    path: /conditions-generales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'apropos\cgu.html.twig'

conditions_generales:
    path: /politique-de-confidentialité
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'apropos\privacypolicy.html.twig'

